server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: employee-service-route
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/v1/employees/**
              filters:
                - StripPrefix=2

            - id: attendance-service-route
              uri: lb://ATTENDANCE-SERVICE
              predicates:
                - Path=/api/v1/attendance/**
              filters:
                - StripPrefix=2

            - id: payroll-service-route
              uri: lb://PAYROLL-SERVICE
              predicates:
                - Path=/api/v1/payroll/**
              filters:
                - StripPrefix=2

            - id: performance-review-service-route
              uri: lb://PERFORMANCE-REVIEW-SERVICE
              predicates:
                - Path=/api/v1/performance-reviews/**
              filters:
                - StripPrefix=2

# Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

