### POST request to employee service
POST http://localhost:8080/api/v1/employees
Content-Type: application/json

{
  "firstName": "Aaron",
  "lastName": "Callanga",
  "email": "onepercentpush@gmail.com",
  "phoneNumber": "+639171234567",
  "hireDate": "2024-05-10",
  "role": "Software Engineer",
  "salary": 60000,
  "status": "ACTIVE",
  "departmentId": 1
}
### aaroncallanga1@example.com