server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AaronCallanga/hrps-configurations/tree/master
          basedir: configs
          clone-on-start: true
          username: ${GITHUB_USERNAME:AaronCallanga}
          password: ${GITHUB_TOKEN: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}
          default-label: master
          refresh-rate: 5
    bus:
      enabled: true
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:http://localhost:9094}


management:
  endpoints:
    web:
      exposure:
        include: busrefresh # POST /actuator/busrefresh - if you want to refresh manually

# Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${HOSTNAME:localhost}
