server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: master #default is main
          search-paths: configs/{application} #search-paths - directory in the github
          uri: https://github.com/AaronCallanga/hrps-configurations
          basedir: ./configs-local #baseDir - directory where it would be cloned
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:http://localhost:9094}

management:
  endpoints:
    jmx:
      exposure:
        include: busrefresh
