server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: master #default is main
          search-paths: configs/{application} #search-paths - directory in the github
          uri: https://github.com/AaronCallanga/hrps-configurations
          basedir: ./configs-local #baseDir - directory where it would be cloned

    bus:
      enabled: true #Allows apps to publish/receive Bus events
      refresh:
        enabled: true #Enables /busrefresh - broadcast config refresh to all services

    stream:
      default-binder: rabbit #Sets which message broker to use
      bindings:
        springCloudBusInput:
          destination: springCloudBus #topic/exchange name (can have multiple queues where message is stored)
          group: ${spring.application.name} #consumer group, create a queue per group
  rabbitmq:
    addresses: ${RABBITMQ_URL:localhost:5672}
    username: ${RABBITMQ_USERNAME:admin_user}
    password: ${RABBITMQ_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include: busrefresh   # exposes /actuator/busrefresh endpoint
